### ISSUE TITLE
Not working on php-integrator 3.1.0?

### ISSUE THREAD

**Issue by claudiofreitas** [coolflyreg/php-integrator-symbol-viewer#1]
Hi coolflyreg, thank you very much for updating the repository!
I've tried installing it, but for some reason it doesn't show the symbols.

I'm on: 
Mac OSX Sierra 10.12.6, 
Atom 1.23.3 x64, 
Php-Integrator 3.1.0

Thank you.

**Comment by coolflyreg** [comment]
@claudiofreitas 
My environment is same as yours except Max OS. But this is not problem.

Please check:
1. Did you install [Project-Manager](https://atom.io/packages/project-manager) for Atom?
2. Did you save your project by Project-Manager?
3. Php-Integrator 3.1.0 is working with PHP 7.1 or higher, are you using PHP7? Please refer to [PHP-Integrator what do I need](https://php-integrator.github.io/#what-do-i-need)
4. Did you index project as manually?

While PHP-Integrator indexing project, it is so slowly. 
After the progress done (there is a progress bar at bottom bar), you can press ctrl+shift+j to show the panel.
